# Generated by Django 2.1 on 2018-08-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='none', max_length=64)),
                ('wx_id', models.CharField(default='none', max_length=64)),
                ('phone', models.CharField(default='none', max_length=64)),
                ('refresh_token', models.CharField(default='none', max_length=64)),
                ('password', models.CharField(default='none', max_length=200)),
                ('openid', models.CharField(default='none', max_length=200)),
                ('nick', models.CharField(default=None, max_length=60)),
                ('avatar', models.CharField(max_length=200)),
                ('info', models.CharField(default=None, max_length=400)),
                ('union_id', models.CharField(default='none', max_length=200)),
            ],
        ),
    ]
