# Generated by Django 2.1 on 2018-08-21 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wx_id',
        ),
    ]
