# Generated by Django 2.1 on 2018-08-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0002_remove_user_wx_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.TextField(default=None, max_length=600),
        ),
    ]
